### PR TITLE
Add 'created' 'updated' readable date to Flow, Task, & Note; Sort Note by 'created' descending; Add '_user' to Flow & Task schema

### PR DESCRIPTION
**Pull request by AshGrowem**
### [Jr. Dev Code Challenge](https://public.3.basecamp.com/p/t2KT5MppyefXursM3937hvf5)
The only assignment I couldn't complete was the last Bonus:
> Display the first and last name of the user that created the Flow/Task/Note

I tried pasting a snippet from [web > resources > user > admin > components > AdminUserListItem.js.jsx](https://github.com/fugitivelabs/task-flow-challenge/blob/main/web/resources/user/admin/components/AdminUserListItem.js.jsx)
```HTML
<td>{user.firstName} {user.lastName}</td>
```
but I couldn't figure out how `user` is inherited. I tried copying relevant code from `AdminUserListItem.js.jsx` as well as other files with `user.` but to no avail. My guess is a parent component passes it down but I couldn't figure out which exactly or how that works.

### CODE REVIEW

**Comment by ffugly** [comment]
Looks good, Ash.  The last bonus was tricky. You have to fetch the User objects associated with the Flow/Task/Note separately from the respective parent views. There are a couple different ways to do this. If you look in https://github.com/fugitivelabs/task-flow-challenge/blob/main/web/resources/task/views/SingleTask.js.jsx you'll see that we're fetching a list of Notes associated with the Task. You would fetch Users in much the same way.  Then you would need pass the user object (or even the entire map) into the child component.

**Comment by AshGrowem** [comment]
This Note fetch?
https://github.com/fugitivelabs/task-flow-challenge/blob/01a4aebe220b6426b1de35a707e0943628435424/web/resources/task/views/SingleTask.js.jsx#L49

Thanks for the explanation Erik!

**Comment by ffugly** [comment]
No. Actually meant the one below it. 
https://github.com/fugitivelabs/task-flow-challenge/blob/01a4aebe220b6426b1de35a707e0943628435424/web/resources/task/views/SingleTask.js.jsx#L50

This will fetch all notes that have a `_task` equal to the `:taskId` in the url

**Comment by AshGrowem** [comment]
Got it!

**Pull request closed without merging**
